---
# nginx
- name: Install nginx
  apt: name=nginx state=present
- name: Start nginx
  service: name=nginx state=started
- name: Create nginx config
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx
# tasks file for gw2019.nginx
